# Generated by Django 2.2.12 on 2021-01-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('num', models.CharField(max_length=18, primary_key=True, serialize=False, unique=True, verbose_name='身份证号')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('gender', models.CharField(max_length=5, verbose_name='性别')),
                ('edu', models.CharField(max_length=20, verbose_name='教育水平')),
            ],
            options={
                'verbose_name': '儿童表',
                'verbose_name_plural': '儿童表',
            },
        ),
    ]
