# Generated by Django 2.2.12 on 2021-01-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='age',
            field=models.IntegerField(default=0, verbose_name='年龄'),
        ),
        migrations.AddField(
            model_name='child',
            name='left_sight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2, verbose_name='左眼视力'),
        ),
        migrations.AddField(
            model_name='child',
            name='right_sight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='右眼视力'),
        ),
    ]
