# Generated by Django 2.2.12 on 2021-01-04 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20210104_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='enter_time',
            field=models.DateField(default=datetime.datetime(2021, 1, 4, 14, 21, 58, 510972), verbose_name='入院时间'),
        ),
        migrations.AddField(
            model_name='child',
            name='temperature',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2, verbose_name='体温'),
        ),
        migrations.AddField(
            model_name='child',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2, verbose_name='体重/kg'),
        ),
    ]
