# Generated by Django 2.2.12 on 2021-01-04 14:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20210104_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('num', models.CharField(max_length=18, primary_key=True, serialize=False, unique=True, verbose_name='工号')),
                ('password', models.CharField(default='000000', max_length=30, verbose_name='密码')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('gender', models.CharField(max_length=5, verbose_name='性别')),
                ('age', models.IntegerField(default=0, verbose_name='年龄')),
                ('edu', models.CharField(max_length=20, verbose_name='学历')),
                ('ethnic_groups', models.CharField(max_length=20, verbose_name='民族')),
                ('Is_manage', models.BooleanField(default=False, verbose_name='是否为管理员')),
                ('brief_introduction', models.CharField(blank=True, max_length=500, null=True, verbose_name='简介')),
            ],
            options={
                'verbose_name_plural': '职员表',
                'verbose_name': '职员表',
            },
        ),
        migrations.AddField(
            model_name='child',
            name='Is_adopted',
            field=models.BooleanField(default=False, verbose_name='已被领养'),
        ),
        migrations.AlterField(
            model_name='child',
            name='enter_time',
            field=models.DateField(default=datetime.datetime(2021, 1, 4, 14, 49, 45, 429504), verbose_name='入院时间'),
        ),
        migrations.CreateModel(
            name='To_doList',
            fields=[
                ('num', models.CharField(max_length=18, primary_key=True, serialize=False, unique=True, verbose_name='安排编号')),
                ('content', models.CharField(max_length=500, verbose_name='内容')),
                ('Is_completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Employee')),
            ],
            options={
                'verbose_name_plural': '待办表',
                'verbose_name': '待办表',
            },
        ),
    ]
