# Generated by Django 2.2.12 on 2021-01-04 15:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20210104_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='enter_time',
            field=models.DateField(default=datetime.datetime(2021, 1, 4, 15, 0, 57, 658054), verbose_name='入院时间'),
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('num', models.CharField(max_length=18, primary_key=True, serialize=False, unique=True, verbose_name='安排编号')),
                ('content', models.CharField(max_length=500, verbose_name='内容')),
                ('Is_audited', models.BooleanField(default=False, verbose_name='是否已审核')),
                ('publisher', models.CharField(max_length=18, verbose_name='申请者')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Employee')),
            ],
        ),
    ]
