# Generated by Django 2.2.12 on 2021-01-04 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20210104_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='to_dolist',
            name='publisher',
            field=models.CharField(default='管理员', max_length=18, verbose_name='发布者'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='publisher',
            field=models.CharField(default='申请者', max_length=18, verbose_name='申请者'),
        ),
        migrations.AlterField(
            model_name='child',
            name='enter_time',
            field=models.DateField(default=datetime.datetime(2021, 1, 4, 15, 4, 6, 239754), verbose_name='入院时间'),
        ),
    ]
