# Generated by Django 2.2.12 on 2021-01-04 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20210104_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step_parent',
            fields=[
                ('num', models.CharField(max_length=18, primary_key=True, serialize=False, unique=True, verbose_name='身份证号')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('gender', models.CharField(max_length=5, verbose_name='性别')),
                ('age', models.IntegerField(default=0, verbose_name='年龄')),
                ('edu', models.CharField(max_length=20, verbose_name='学历')),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=2, verbose_name='月收入')),
                ('Has_child', models.BooleanField(default=False, verbose_name='是否已有子女')),
                ('temperature', models.DecimalField(decimal_places=2, default=0, max_digits=2, verbose_name='体温')),
                ('right_sight', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='右眼视力')),
                ('left_sight', models.DecimalField(decimal_places=2, default=0, max_digits=2, verbose_name='左眼视力')),
                ('Is_adopted', models.BooleanField(default=False, verbose_name='已被领养')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.CharField(default='无', max_length=20, verbose_name='地址'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(default='待入职', max_length=10, verbose_name='岗位'),
        ),
        migrations.AddField(
            model_name='employee',
            name='tele',
            field=models.CharField(default='无', max_length=20, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='child',
            name='enter_time',
            field=models.DateField(default=datetime.datetime(2021, 1, 4, 15, 21, 2, 31236), verbose_name='入院时间'),
        ),
    ]
