# Generated by Django 2.2.12 on 2021-01-04 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_auto_20210104_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audit',
            options={'verbose_name': '审核表', 'verbose_name_plural': '审核表'},
        ),
        migrations.AlterModelOptions(
            name='step_parent',
            options={'verbose_name': '领养人资料表', 'verbose_name_plural': '领养人资料表'},
        ),
        migrations.RemoveField(
            model_name='step_parent',
            name='Is_adopted',
        ),
        migrations.RemoveField(
            model_name='step_parent',
            name='left_sight',
        ),
        migrations.RemoveField(
            model_name='step_parent',
            name='right_sight',
        ),
        migrations.RemoveField(
            model_name='step_parent',
            name='temperature',
        ),
        migrations.AddField(
            model_name='step_parent',
            name='address',
            field=models.CharField(default='无', max_length=20, verbose_name='地址'),
        ),
        migrations.AddField(
            model_name='step_parent',
            name='tele',
            field=models.CharField(default='无', max_length=20, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='child',
            name='enter_time',
            field=models.DateField(default=datetime.datetime(2021, 1, 4, 15, 22, 6, 893106), verbose_name='入院时间'),
        ),
    ]
