# Generated by Django 2.2.12 on 2021-01-05 20:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_auto_20210105_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Employee'),
        ),
        migrations.AlterField(
            model_name='child',
            name='enter_time',
            field=models.DateField(default=datetime.datetime(2021, 1, 5, 20, 28, 8, 771815), verbose_name='入院时间'),
        ),
        migrations.AlterField(
            model_name='to_dolist',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='App.Employee'),
        ),
        migrations.AlterField(
            model_name='to_dolist',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publisher', to='App.Employee'),
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
